### ISSUE TITLE
Rain sometimes isn't cleared after sleeping through the night.

### ISSUE THREAD

**Issue by Guardian259** [Giggitybyte/SleepWarp#1]
Sleeping through the night does not guaranty that the weather will be set to clear if weather was previously rainy or stormy.

**Comment by Giggitybyte** [comment]
Can I get a little more detail? What are the steps to reproduce this issue?
Sleep Warp should [clear the weather](https://github.com/Giggitybyte/SleepWarp/blob/52c8993ad92b7575d287396f2c323c7df898b31b/src/main/java/me/thegiggitybyte/sleepwarp/mixin/ServerWorldMixin.java#L100) if it's day, just before waking all players.

**Comment by Giggitybyte** [comment]
I've been able to reproduce this, but it's difficult to track down exactly what causes this; it seems that distance between players might be a factor.
