### ISSUE TITLE
Crash on Fabric server

### ISSUE THREAD

**Issue by Quplet** [Giggitybyte/SleepWarp#13]
Crash on Fabric server, occurs at the end of the night right before it wakes you up.

Mod version v2.0.0-rc1

Also for some reason it always says the server is behind by either 40 or 41 ticks specifically at the beginning of the time speed up. It doesn't seem to affect much tho. 
[2023-04-17-7.log](https://github.com/Giggitybyte/SleepWarp/files/11257124/2023-04-17-7.log)

**Comment by Giggitybyte** [comment]
This should be resolved in [2.0.0-rc3](https://modrinth.com/mod/sleep-warp/version/2.0.0_rc3+1.19.4)
