### ISSUE TITLE
sleepwarp provides a broken implementation to the Mod Menu API

### ISSUE THREAD

**Issue by WalEl6512** [Giggitybyte/SleepWarp#16]
> Mod Menu
> Render thread
> Mod sleepwarp provides a broken implementation of ModMenuApi
> java.lang.NoClassDefFoundError: dev/isxander/yacl/api/Controller
>	at java.base/java.lang.Class.forName0(Native Method)
>	at java.base/java.lang.Class.forName(Class.java:467)
>	at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50)
>	at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117)
>	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53)
>	at com.terraformersmc.modmenu.ModMenu.lambda$onInitializeClient$1(ModMenu.java:74)
>	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
>	at com.terraformersmc.modmenu.ModMenu.onInitializeClient(ModMenu.java:70)
>	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
>	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
>	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53)
>	at net.minecraft.class_310.<init>(class_310.java:468)
>	at net.minecraft.client.main.Main.main(Main.java:198)
>	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462)
>	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
>	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
> Caused by: java.lang.ClassNotFoundException: dev.isxander.yacl.api.Controller
>	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
>	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
>	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)
>	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112)
>	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
>	... 16 more

This does not lead to a crash but does make it impossible to use the mod menu on the mod

**Comment by Giggitybyte** [comment]
SleepWarp uses [YetAnotherConfigLib](https://modrinth.com/mod/yacl/versions?g=1.19.4&g=1.19.2&l=fabric) (YACL) as the implementation for ModMenu. As such, YACL is a dependency which also needs to be installed to access SleepWarp settings from ModMenu.

**Comment by WalEl6512** [comment]
adding the library did resolve the isse yep.
