### ISSUE TITLE
Game starts to freeze for a couple of seconds after sleeping

### ISSUE THREAD

**Issue by rottakore** [Giggitybyte/SleepWarp#18]
Hello, I don't know if I'm opening the issue correctly, but your mod apparently makes the game freeze a lot of times after you sleep, and the freezes increase if you sleep more and more. I've already tested and this freezing doesn't occur if I do not sleep.

Mods:
  [✔] [Universal]Immersive Structures-2.0.7a
  [✔] AdditionalStructures-1.19.x-(v.4.1.1)
  [✔] adventurez-1.4.18
  [✔] alternate-current-mc1.19-1.5.0
  [✔] angling-1.0.1
  [✔] antighost-1.19.1-fabric0.58.5-1.1.5
  [✔] appleskin-fabric-mc1.19-2.4.1
  [✔] architectury-6.5.82-fabric
  [✔] autotag-2.0.0+1.19
  [✔] bendy-lib-fabric-2.1.1
  [✔] betterbeds-1.2.0
  [✔] betterbiomeblend-1.19.0-1.3.6-fabric
  [✔] bettercombat-fabric-1.7.1+1.19
  [✔] BetterPingDisplay-Fabric-1.19.2-1.1.1
  [✔] BetterThirdPerson-Fabric-1.19-1.9.0
  [✔] blur-2.6.0
  [✔] c2me-fabric-mc1.19.2-0.2.0+alpha.9.9
  [✔] CameraOverhaul-1.4.0-fabric-universal
  [✔] caracal-1.19.2-2.0.2
  [✔] carryon-fabric-1.19.2-2.0.5.11
  [✔] charmonium-fabric-1.19.2-4.2.1
  [✔] CITResewn-1.1.2+1.19.2
  [✔] ClearDespawn-fabric-1.19.2-1.1.10
  [✔] Clumps-fabric-1.19.2-9.0.0+14
  [✔] continuity-2.0.2+1.19
  [✔] crawl-0.11.1
  [✔] creeperoverhaul-2.0.9-fabric
  [✔] crittersandcompanions-fabric-1.19.2-1.0.3
  [✔] ctov-3.2.1
  [✔] darkness-fabric-mc119-2.0.101
  [✔] dawn-3.5.0
  [✔] deeperdarker-fabric-1.1.6-fabric
  [✔] DetailArmorBar-2.6.2+1.19-fabric
  [✔] direbats-3.1.0+1.19.2
  [✔] DisableCustomWorldsAdvice-3.0
  [✔] DripSounds-1.19-0.3.0
  [✔] duckling-2.0.8-fabric
  [✔] dusk-fabric-1.19.1-2.2
  [✔] dynamiccrosshair-5.6.1+1.19.2-fabric
  [✔] dynamiccrosshair-compat-3.3.1+1.19.2
  [✔] eating-animation-1.9.1
  [✔] elytraslot-fabric-6.1.1+1.19.2
  [✔] enhancedblockentities-0.7.2+1.19.2
  [✔] Entity_Collision_FPS_Fix-fabric-1.19-2.0.0.0
  [✔] entity_model_features_fabric_1.19.2-0.2.9
  [✔] entity_texture_features_fabric_1.19.2-4.4.4
  [✔] entityculling-fabric-1.6.1-mc1.19.2
  [✔] Essential-fabric_1-19
  [✔] exordium-fabric-1.0.2-mc1.19.2
  [✔] extrasounds-2.3.1+1.19.2-1.19.1
  [✔] fabric-api-0.76.0+1.19.2
  [✔] fabric-language-kotlin-1.9.4+kotlin.1.8.21
  [✔] fabric-seasons-2.2+1.19
  [✔] FabricShieldLib-1.7-1.19.2
  [✔] fallingleaves-1.13.0+1.19.2
  [✔] FallingTree-1.19.2-3.10.0
  [✔] fastfurnace-1.19.2-5
  [✔] Fastload+1.18.2-1.20-3.4.0
  [✔] fastquit-2.1.0+1.19-1.19.2
  [✔] ferritecore-5.0.3-fabric
  [✔] firstperson-fabric-2.2.2-mc1.19.2
  [✔] ForgeConfigAPIPort-v4.2.11-1.19.2-Fabric
  [✔] FpsReducer2-fabric-1.19.2-2.1
  [✔] From-The-Fog-1.19-v1.9-Forge-Fabric
  [✔] geckolib-fabric-1.19-3.1.40
  [✔] goodall-1.2.0-fabric
  [✔] held-item-info-1.4.0
  [✔] ImmediatelyFast-1.1.12+1.19
  [✔] Incendium_1.19.3_v5.1.6
  [✔] indium-1.0.9+mc1.19.2
  [✔] inmis_retextured-2.7.0-1.19
  [✔] inventorymanagement-1.1.0+1.19
  [✔] item-model-fix-1.0.3+1.19
  [✔] jumpprooffarmland-1.19.2-1.0.1
  [✔] keep-some-inventory-v1.2.0
  [✔] konkrete_fabric_1.6.1_MC_1.19.1-1.19.2
  [✔] krypton-0.2.1
  [✔] lambdabettergrass-1.3.0+1.19
  [✔] lambdynamiclights-2.2.0+1.19.2
  [✔] language-reload-1.5.6+1.19.2
  [✔] lazydfu-0.1.3
  [✔] lithium-fabric-mc1.19.2-0.11.1
  [✔] livingthings-fabric-1.19.2-2.0.0-rc1
  [✔] lunade-fastanim-1.5.7
  [✔] make_bubbles_pop-0.1.0-1.19
  [✔] megaparrot-1.0.7-1.19.2
  [✔] memoryleakfix-fabric-1.17+-1.0.0
  [✔] Mimic-fabric-1.19.1-1.2.38
  [✔] mining-helmet-mod-1.1.1+1.19
  [✔] MobPlaques-v4.0.1-1.19.2-Fabric
  [✔] moderate-loading-screen-1.1.3+1.19
  [✔] modernworldcreation_fabric_1.0.0_MC_1.19-1.19.2
  [✔] modmenu-4.2.0-beta.2
  [✔] moreculling-1.19.1-0.17.0
  [✔] MoreCullingExtra-1.1-backport_1.19.2
  [✔] more-ladders-1.19.2-1.1.0
  [✔] moremobvariants-1.0.1-1.19.2
  [✔] mostructures-1.4.3+1.19.2
  [✔] mvs-2.5.10-1.19.2
  [✔] mythicmetals-0.17.3+1.19.2
  [✔] naturalist-fabric-3.0.2-1.19.2
  [✔] NoChatReports-FABRIC-1.19.2-v1.13.12
  [✔] notenoughanimations-fabric-1.6.2-mc1.19.2
  [✔] Nullscape_1.19.3_v1.2.1
  [✔] optigui-2.1.0-beta.2
  [✔] ottah-A1-pre_4
  [✔] owo-lib-0.9.3+1.19
  [✔] player-animation-lib-fabric-1.0.2
  [✔] PresenceFootsteps-1.6.4
  [✔] PuzzlesLib-v4.4.0-1.19.2-Fabric
  [✔] raised-fabric-1.19.2-1.2.2
  [✔] recipe-book-is-pain-0.9.3-1.19.2
  [✔] Recipe-Unlocker
  [✔] reeses_sodium_options-1.4.9+mc1.19.2-build.67
  [✔] resourcefulconfig-fabric-1.19.2-1.0.20
  [✔] riding_partners-1.19.3-1.0.0-fabric
  [✔] servercore-1.3.3-1.19.2
  [✔] shulkerboxtooltip-fabric-3.2.2+1.19.2
  [✔] simplyswords-fabric-1.43.0-1.19.2
  [✔] skylorlib-1.5.1
  [✔] sleepwarp-2.0.0+1.19.2 <-
  [✔] smoke-suppression-1.0.13+MC1.19-1.19.2
  [✔] Smooth Swapping 0.6 (1.19.2)-0.6
  [✔] smoothboot-fabric-1.19-1.7.1
  [✔] snow-under-trees-fabric-1.0.0+1.19.2
  [✔] sodium-extra-0.4.16+mc1.19.2-build.90
  [✔] sodium-fabric-mc1.19.2-0.4.4+build.18
  [✔] soulslike-weaponry-0.9.9.3
  [✔] soundphysics-fabric-1.19.2-1.0.18
  [✔] species-1.1-fabric
  [✔] stackable-0.2.2
  [✔] starlight-1.1.1+fabric.ae22326
  [✔] statuseffecttimer-1.1.1+1.19
  [✔] Structory_Towers_1.19_v1.0.1
  [✔] Structory-1.19-v1.3
  [✔] tectonic-mod-mc1.19.2-v1.1.10
  [✔] Terralith_1.19.3_v2.3.7b
  [✔] The_Graveyard_2.3.2_(FABRIC)_for_1.19.2
  [✔] tia-1.19.2-1.0.0
  [✔] toolleveling-fabric-1.19.2-1.4.1
  [✔] tooltipfix-1.1.1-1.19
  [✔] trinkets-3.4.2
  [✔] universal_ores-1.4.2
  [✔] variant_shields-1.0.3
  [✔] vcinteraction-1.19.2-1.0.3
  [✔] visuality-0.5.6
  [✔] vmp-fabric-mc1.19.2-0.2.0+beta.7.29-all
  [✔] voicechat-fabric-1.19.2-2.4.8
  [✔] Weeping-Angels-43.0.9-fabric
  [✔] wondrouswilds-1.19.2-1.1.6
  [✔] wraith-alloy-forgery-2.0.20+1.19
  [✔] wraith-waystones-3.0.7+mc1.19.2
  [✔] YetAnotherConfigLib-2.2.0-for-1.19.2
  [✔] YungsApi-1.19.2-Fabric-3.8.9
  [✔] YungsBetterDesertTemples-1.19.2-Fabric-2.2.2
  [✔] YungsBetterDungeons-1.19.2-Fabric-3.2.1
  [✔] YungsBetterMineshafts-1.19.2-Fabric-3.2.0
  [✔] YungsBetterNetherFortresses-1.19.2-Fabric-1.0.5
  [✔] YungsBetterOceanMonuments-1.19.2-Fabric-2.1.0
  [✔] YungsBetterStrongholds-1.19.2-Fabric-3.2.0
  [✔] YungsBetterWitchHuts-1.19.2-Fabric-2.1.0
  [✔] YungsExtras-1.19.2-Fabric-3.1.0

**Comment by Giggitybyte** [comment]
Please upload your SleepWarp config file and a video clip of the issue. 
Does this happen when SleepWarp is the only mod installed?

**Comment by Giggitybyte** [comment]
Closing due to a lack of activity.
