### ISSUE TITLE
ETA of 1.20? Or just change the version in fabric.mod.json?

### ISSUE THREAD

**Issue by Mudxiej** [Giggitybyte/SleepWarp#19]
You know what I'm here for, so hands up and answer CAREFULLY :DD

**Comment by inftord** [comment]
one moment

**Comment by Giggitybyte** [comment]
There are a few things that need to be updated. Soon™

**Comment by Mudxiej** [comment]
> There are a few things that need to be updated. Soon™

Damn, it was quick. Ty v v much!
