### ISSUE TITLE
Sleeping through the night makes growing melons (and possibly pumpkins) disappear

### ISSUE THREAD

**Issue by SplendidAlakey** [Giggitybyte/SleepWarp#2]
**MC** 1.18.2
**Fabric** API 0.47.10
**SleepWarp** 1.1.1

To reproduce:

1. Set both tickBlockEntities and tickChunks to true
2. Plant a melon/pumpkin seed, let it reach 86% maturity (a step before the melon would fully grow)
3. Go to sleep

Expected result: a melon grows out

Actual result: the stem reaches full maturity, but no melon grows out

The issue doesn't happen if you just let melons grow before going to sleep.

Let me know if a log is necessary.

**Comment by Giggitybyte** [comment]
I don't believe this is an issue. In vanilla, once a pumpkin or melon stem reaches full maturity, it will not immediately spawn a pumpkin or melon.
