### ISSUE TITLE
Incompatibility with C2ME

### ISSUE THREAD

**Issue by JackiTacki** [Giggitybyte/SleepWarp#21]
Causes the world to become unsavable after a sleep cycle.

**Comment by JackiTacki** [comment]
UPDATE 

Compat undetermined, Causes world to become unsavable as a whole in 1.20(?)

**Comment by Giggitybyte** [comment]
I am unable to reproduce this. Are you certain SleepWarp is the issue? Can you save your world when SleepWarp is not present in your mods folder?

**Comment by JackiTacki** [comment]
Mhm.

**Comment by JackiTacki** [comment]
Incompat found!

Apologies for that. Apparently it conflicts with C2ME, A chunk optimization mod. Resolved! A server I opened for testing helped me with this.

**Comment by Giggitybyte** [comment]
Ah, glad you narrowed it down! Just got another report on Discord of a different conflict with C2ME. I'll take a look and see if I can resolve it on my end; if you have a log with a stacktrace I'd appreciate it you could upload it so I can attempt to debug your issue.

**Comment by Giggitybyte** [comment]
After looking into it further, I would have to change how I tick the world to make SleepWarp compatible with C2ME. C2ME is lower on my list of mods to be compatible with, so it'd be something that would come after porting the project to the Architectury platform to support Forge and Quilt.
