### ISSUE TITLE
Incompatible With Real Camera

### ISSUE THREAD

**Issue by lostopkk** [Giggitybyte/SleepWarp#22]
minecraft version: 1.20

can't sleep

https://modrinth.com/mod/real-camera

**Comment by Giggitybyte** [comment]
I cannot reproduce this; are you certain SleepWarp is your issue?

https://github.com/Giggitybyte/SleepWarp/assets/19187704/b25e7edb-91e0-4919-84a1-ebfff0dd4be7

**Comment by lostopkk** [comment]
> I cannot reproduce this; are you certain SleepWarp is your issue?
> 
> https://github.com/Giggitybyte/SleepWarp/assets/19187704/b25e7edb-91e0-4919-84a1-ebfff0dd4be7
> 
> 

so it must be another mod, I'll investigate and then send the issue here again, thanks and sorry for anything
