### ISSUE TITLE
Breaks redstone pen mod parts when sleeping

### ISSUE THREAD

**Issue by hellozyemlya** [Giggitybyte/SleepWarp#24]
Playing with sleep warp and https://www.curseforge.com/minecraft/mc-mods/redstone-pen breaks schemas build with pen.
Minecraft 1.19.4, fabric loader.

Mods:
  [✔] AdditionalStructures-1.19.x-(v.4.1.1)
  [✔] alternate-current-mc1.19-1.6.0
  [✔] architectury-8.1.87-fabric
  [✔] autotorch-mc1.19.4-1.2.3+build.4
  [✔] badpackets-fabric-0.4.1
  [✔] Chunky-1.3.74
  [✔] cloth-config-10.0.96-fabric
  [✔] DistantHorizons-1.6.11a-1.19.4
  [✔] fabric-api-0.83.0+1.19.4
  [✔] fabric-language-kotlin-1.9.5+kotlin.1.8.22
  [✔] FallingTree-1.19.4-3.12.2
  [✔] immersive_aircraft-0.5.0+1.19.4-fabric
  [✔] InventoryProfilesNext-fabric-1.19.4-1.10.3
  [✔] libIPN-fabric-1.19.4-3.0.2
  [✔] litematica-fabric-1.19.4-0.14.3
  [✔] malilib-fabric-1.19.4-0.15.4
  [✔] modmenu-6.2.3
  [✔] owo-lib-0.10.3+1.19.4
  [✔] redstonepen-1.19.4-fabric-1.4.23
  [✔] RoughlyEnoughItems-11.0.621
  [✔] sleepwarp-2.0.0+1.19.4
  [✔] sodium-fabric-mc1.19.4-0.4.10+build.24
  [✔] wraith-waystones-3.1.1+mc1.19.4
  [✔] wthit-fabric-7.3.2
  [✔] Xaeros_Minimap_23.4.4_Fabric_1.19.4
  [✔] XaerosWorldMap_1.30.3_Fabric_1.19.4

**Comment by Giggitybyte** [comment]
Unfortunately, the developer for Redstone Pen does not have their source code available publicly so I cannot properly debug this and attempt to figure out a solution on my end.
