### ISSUE TITLE
Time issue.

### ISSUE THREAD

**Issue by The-Gmann** [Giggitybyte/SleepWarp#3]
It feels like sleeping doesn't make you skip the appropriate amount of time, but instead just some. I want an option for sleeping to pass the actual time that you would go through in an actual night, my furnaces barely did anything overnight, i have the ticking blocks and chunks enabled in the settings. (Playing on 1.16.5)

**Comment by Giggitybyte** [comment]
> I want an option for sleeping to pass the actual time that you would go through in an actual night

Sleep warp does this already! During each game tick, up to `maxTimeAdded` ticks (default 60) will be added to the world time while sleeping to progress through the night. When `tickBlockEntities` and `tickChunks` are set to `true`, things like furnaces and crops will be ticked at an equal rate to simulate the passage of time. If you can read Java, you can see the exact logic [here](https://github.com/Giggitybyte/SleepWarp/blob/1d884e142f26d49779847851e23ae376419f56b3/src/main/java/me/thegiggitybyte/sleepwarp/mixin/ServerWorldMixin.java#L71).

> my furnaces barely did anything overnight

The night in Minecraft is only about 7 minutes long, I'm not sure what you were expecting.
