### ISSUE TITLE
TAKE DOWN 1.20.* versions!!

### ISSUE THREAD

**Issue by Unleashed75** [Giggitybyte/SleepWarp#30]
You are breaking and wrecking peoples worlds!!
Take them down on all sites till you fix the f'in problem. Stop being a jerk!!

**Comment by KaylaSolace** [comment]
issue #25, #28 for reference

**Comment by Unleashed75** [comment]
> what is the problem??? maybe explain??

They know what the problem is, they have replied and are letting others still download this bugged out 1.20-1.20.1 mod. A good person would of taken it down by now because of how bugged it is. It's not about turning this or that feature off to fix it because by then it's already wrecked peoples worlds, wasted peoples time looking for the problem, a problem that they knew about weeks before I even found it.
I don't need to explain what the problem is when it's already been reported a couple times now and other bugs. They are just leaving it up to wreck more peoples worlds.
This is a message to them to at least do the right thing and Take Down the bugged version!
It doesn't need "issue #25 for reference" when they know

**Comment by KaylaSolace** [comment]
its more for people like me who just see this issue randomly and hadnt seen the others yet because its at the top of the list

**Comment by Giggitybyte** [comment]
I don't appreciate your tone and your baseless assumptions. You do not know me or my life.

**Comment by KaylaSolace** [comment]
> I don't appreciate your tone and your baseless assumptions. You do not know me or my life.

While I do think their tone was rude, and have read your post on the discord, I do think it's a little bit unreasonable to say you didn't have time to do something as simple as take down a version you *already were aware* was causing issues, or upload a version with the block ticking feature disabled. The fact that we had to bother Modrinth to remove it was a bit silly. 

I am a software developer myself and I am often quite busy, but it really doesn't take that long to take down an errant version of your code from websites.
