### ISSUE TITLE
Update to 1.20.1

### ISSUE THREAD

**Issue by MbtMarco** [Giggitybyte/SleepWarp#31]
<img width="1253" alt="Screenshot 2023-07-30 alle 14 54 04" src="https://github.com/Giggitybyte/SleepWarp/assets/124934175/6904da5a-f56f-4c68-a020-7358aa5a3470">

**Comment by Unleashed75** [comment]
It was updated but due to a major bug, it was taken down. I do hope they fix it as it is a nice mod that makes people sleep more often

**Comment by Giggitybyte** [comment]
As mentioned above; see #25.
