### ISSUE TITLE
[Feature Request] Add a settings menu within Mod Menu

### ISSUE THREAD

**Issue by ehllie** [Giggitybyte/SleepWarp#4]
It's possible to access some mods settings from within the mod list that the Mod Menu mod provides. It would be handy to have SleeWarp integrate into that so that we could change settings like the tickrate from within the game.

**Comment by Giggitybyte** [comment]
I'll implement mod menu support in a day or two when I have some spare time 👍

**Comment by Giggitybyte** [comment]
Still on the to-do list ✅

**Comment by EGOIST1372** [comment]
@Giggitybyte any news on this matter? 
Also I have a question and I didn't want to create an issue to ask it so I ask it here.
Is it possible to disable the tick when you sleep? (just like the vanilla sleeping)

**Comment by Giggitybyte** [comment]
This will be added alongside an upcoming update to 1.19.3

**Comment by Giggitybyte** [comment]
This has been implemented in [version 2.0.0](https://github.com/Giggitybyte/SleepWarp/releases/tag/2.0.0) 😄
