### ISSUE TITLE
[Feature Request] Display a timer for how long until dawn

### ISSUE THREAD

**Issue by Lancelotbronner** [Giggitybyte/SleepWarp#8]
Love the mod! I tried not telling my players about the mechanic and they were very confused 5/5.

If a little timer had been displaying the time until dawn they would have been less confused. SOmething like this:

![Someone sleeping with a timer until dawn](https://github.com/Steveplays28/realisticsleep/raw/main/Minecraft%20RealisticSleep%20mod.gif)

**Comment by Giggitybyte** [comment]
This has been implemented in [version 2.0.0](https://github.com/Giggitybyte/SleepWarp/releases/tag/2.0.0) 😄
